### ISSUE TITLE
[WARNI] csssprites does not support your node v2.0.0 出现这样的问题怎么办？切换本地node版本？

### ISSUE THREAD

**Issue by qintengfei** [fex-team/fis-plus#55]
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED 10.46.175.143:8090
    at Object.exports._errnoException (util.js:843:11)
    at exports._exceptionWithHostPort (util.js:866:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1022:14)

**Comment by xiangshouding** [comment]
升级你的 fis-plus 到最新版本

**Comment by xiangshouding** [comment]
额，抱歉，貌似你用的 iojs ，iojs 还没有支持；等 iojs 和 nodejs 合并后再支持；
