### ISSUE TITLE
为什么fis+使用fisp release -pr xxx 无法像fis一样自动打包

### ISSUE THREAD

**Issue by w2230030100** [fex-team/fis-plus#64]
我在配置文件里也加了如下代码
```
fis.config.set('modules.postpackager', 'simple');
fis.config.set('settings.postpackager.simple.autoCombine', true);
```
但是 当打-mop命令的时候就事无法将文件合并到一起

**Comment by w2230030100** [comment]
http://solar.baidu.com/autopack/doc 这个链接为什么打不开 有别的资料吗

**Comment by w2230030100** [comment]
fisp不支持类似fis的那种自动打包吗

**Comment by w2230030100** [comment]
receiver.php这个文件我下载下来放到我的本地服务器上了 然后我用
```
fis.config.set('deploy', {
    //使用fis release --dest static来使用这个配置
    remote: [{
        //如果配置了receiver，fis会把文件逐个post到接收端上
        receiver : 'http://www.example.com/path/to/receiver.php',
        //从产出的结果的static目录下找文件
        from : '/static',
        //上传目录从static下一级开始不包括static目录
        subOnly : true,
        //保存到远端机器的/home/fis/www/static目录下
        //这个参数会跟随post请求一起发送
        to : '/home/fis/www/',
        //某些后缀的文件不进行上传
        exclude : /.*\.(?:svn|cvs|tar|rar|psd).*/
    },
    {
        //如果配置了receiver，fis会把文件逐个post到接收端上
        receiver : 'http://www.example.com/path/to/receiver.php',
        //从产出的结果的config目录下找文件
        from : '/config',
        //保存到远端机器的/home/fis/www/config目录下
        //这个参数会跟随post请求一起发送
        to : '/home/fis/www/',
        //某些后缀的文件不进行上传
        exclude : /.*\.(?:svn|cvs|tar|rar|psd).*/
    },
    {
        //如果配置了receiver，fis会把文件逐个post到接收端上
        receiver : 'http://www.example.com/path/to/receiver.php',
        //从产出的结果的template目录下找文件
        from : '/config',
        //保存到远端机器的/home/fis/www/template目录下
        //这个参数会跟随post请求一起发送
        to : '/home/fis/www/',
        //某些后缀的文件不进行上传
        exclude : /.*\.(?:svn|cvs|tar|rar|psd).*/
    },
    {
        //如果配置了receiver，fis会把文件逐个post到接收端上
        receiver : 'http://www.example.com/path/to/receiver.php',
        //从产出的结果的plugin目录下找文件
        from : '/plugin',
        //保存到远端机器的/home/fis/www/plugin目录下
        //这个参数会跟随post请求一起发送
        to : '/home/fis/www/',
        //某些后缀的文件不进行上传
        exclude : /.*\.(?:svn|cvs|tar|rar|psd).*/
    }]
});
```
进行了上传 发现报错 内容如下
```
bogon:myfisp ningfujun$ fisp release -r kelepc -d remote

 Ω ................................................................ 263ms
/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:63
        throw err
              ^
Error: upload file [/page/test/index.tpl] to [] by receiver [http://127.0.0.1/fisr/fis-command-release/tools/receiver.php] error [1]
    at Object.exports.error (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-deploy-default/index.js:76:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/fis-plus/node_modules/fis/node_modules/fis-kernel/lib/util.js:835:21)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

```
具体我该怎么做才能上传上去

**Comment by w2230030100** [comment]
话说大大们今天都不在吗 还是我问的太2了

**Comment by w2230030100** [comment]
其实我要那个简版的页面级的自动打包就够用了 该怎么设置啊 求大大们告知啊

**Comment by w2230030100** [comment]
又遇到个问题 fis+怎么在js文件中进行资源定位 __uri(xxx)貌似不识别 我想定位个swf文件

**Comment by w2230030100** [comment]
文档太少了 很多东西不知道怎么弄

**Comment by xiangshouding** [comment]
@w2230030100 

遇到啥问题了？

**Comment by w2230030100** [comment]
@xiangshouding 
第一个问题是不知道fis+怎么自动化打包 就是类似fis的那种针对单页面进行1个css和1个js的那种 我看教程有个自动化的链接是这个http://solar.baidu.com/autopack/doc 但是打不开 
第二个是我把教程里的receiver.php的文件下载下来放到本地服务器上 然后我release -d remote出错 防火墙已关
