### ISSUE TITLE
fisp server start fail

### ISSUE THREAD

**Issue by Gordon-Gu** [fex-team/fis-plus#70]
[ERROR] fis-server fails to start at port [8080], error: timeout
java -- v1.7.0
php-cgi -- v5.3.5

![image](https://cloud.githubusercontent.com/assets/6930965/8538374/f37889a2-249d-11e5-8783-db9b5620a3b4.png)
![image](https://cloud.githubusercontent.com/assets/6930965/8538377/fe31fb1c-249d-11e5-8869-48e3ff890b86.png)

改了端口，延长了时间，还是报错

**Comment by xiangshouding** [comment]
那就timeout改得大一点咯；

```
fisp server start --timeout 100000
```

**Comment by Gordon-Gu** [comment]
改大了的结果
![image](https://cloud.githubusercontent.com/assets/6930965/8538490/766d7222-249f-11e5-91a7-a1e2a7b35a88.png)

**Comment by xiangshouding** [comment]
@Gordon-Gu 是否是 php-cgi 工作不正常？

验证方法：
0. 打开一个 cmd
0. 输入命令 php-cgi -v
0. 看输出是否正常

**Comment by g8up** [comment]
>fis3 server start
```
 [INFO] Currently running fis3 (/usr/local/lib/node_modules/fis3/)
checking php-cgi support : v5.6.33
checking java support : v9.0.4
starting fis-server ... fail
Exception in thread "main" java.lang.NullPointerException
/usr/local/lib/node_modules/fis3/lib/log.js:201
    throw err
    ^

Error: fis-server fails to start at port [8080], error: unknown
    at Object.exports.error (/usr/local/lib/node_modules/fis3/lib/log.js:192:11)
    at Socket.<anonymous> (/usr/local/lib/node_modules/fis3-server-smarty/vendor/server.js:159:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

> php-cgi -v
```
PHP 5.6.33 (cgi-fcgi) (built: Jan  7 2018 11:12:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
